version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      # Admin account
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # DB
      DB_VENDOR: mariadb
      DB_ADDR: 100.100.10.177
      DB_PORT: 3306
      DB_DATABASE: keycloak_dev
      DB_USER: e1264
      DB_PASSWORD: inveni@2020
    command:
      - "-b"
      - "0.0.0.0"
  eurekaserver:
    image: kds.inveniacorp.com/damu/msa-base/eureka-server:latest
    restart: on-failure
    ports:
      - "8761:8761"
    build:
      context: ./eureka-server
  configserver:
    image: kds.inveniacorp.com/damu/msa-base/config-server:latest
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
    build:
      context: ./config-server
    depends_on:
      - eurekaserver
  apigateway:
    image: kds.inveniacorp.com/damu/msa-base/api-gateway:latest
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_URI: "http://100.100.15.82:8080/auth" # 호스트 주소
      KEYCLOAK_REALM: "service"
      KEYCLOAK_REDIRECT_URI: "http://localhost:8000" # 게이트웨이 주소
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
    build:
      context: ./api-gateway
    depends_on:
      - eurekaserver
