version: '3.9'
services:
  eurekaserver:
    image: ghcr.io/zmmx011/eureka-server:latest
    ports:
      - "8761:8761"
  configserver:
    image: ghcr.io/zmmx011/config-server:latest
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
  licensingservice:
    image: ghcr.io/zmmx011/licensing-service:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      ENCRYPT_KEY: "damu"
  organizationservice:
    image: ghcr.io/zmmx011/organization-service:latest
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "damu"
