version: '3.9'
services:
  keycloak:
    container_name: keycloak
    image: kds.inveniacorp.com/keycloak-theme/keycloak
    networks:
      - msa
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      # Admin account
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # DB
      DB_VENDOR: mariadb
      DB_ADDR: 100.100.10.177
      DB_PORT: 3306
      DB_DATABASE: keycloak_dev
      DB_USER: e1264
      DB_PASSWORD: inveni@2020
    command:
      - "-b"
      - "0.0.0.0"

  eurekaserver:
    container_name: eureka-server
    image: kds.inveniacorp.com/dev/msa-base/eureka-server:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8761:8761"

  configserver:
    container_name: config-server
    image: kds.inveniacorp.com/dev/msa-base/config-server:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
    depends_on:
      - eurekaserver

  apigateway:
    container_name: api-gateway
    image: kds.inveniacorp.com/dev/msa-base/api-gateway:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_URI: "http://100.100.15.82:8080/auth" # 호스트 주소
      KEYCLOAK_REALM: "service"
      KEYCLOAK_REDIRECT_URI: "http://localhost:8000" # 게이트웨이 주소
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
    depends_on:
      - eurekaserver

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    container_name: rabbitmq-stream
    networks:
      - msa
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "inveni@2021"

networks:
  msa:
    external: true
    name: msa
