version: '3.9'
services:
  eurekaserver:
    container_name: eureka-server
    image: kds.inveniacorp.com/dev/msa-base/eureka-server:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8761:8761"
    environment:
      TZ: "Asia/Seoul"

  configserver:
    container_name: config-server
    image: kds.inveniacorp.com/dev/msa-base/config-server:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE: dev
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
    depends_on:
      - eurekaserver

  apigateway:
    container_name: api-gateway
    image: kds.inveniacorp.com/dev/msa-base/api-gateway:latest
    networks:
      - msa
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Seoul"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "damu"
      CONFIGSERVER_URI: "http://configserver:8888"
    depends_on:
      - eurekaserver
      - configserver

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    container_name: rabbitmq-stream
    networks:
      - msa
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: "Asia/Seoul"
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "inveni@2021"

networks:
  msa:
    external: true
    name: msa
