server:
  port: 8000
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: "http://eurekaserver:8761/eureka/" # 유레카 서비스 위치
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: licensing-service
          uri: lb://LICENSINGSERVICE
          predicates:
            - Path=/licensing-service/**
        - id: organization-service
          uri: lb://ORGANIZATIONSERVICE
          predicates:
            - Path=/organization-service/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
