server:
  port: 8000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: licensing-service
          uri: lb://LICENSINGSERVICE
          predicates:
            - Path=/licensing-service/**
        - id: organization-service
          uri: lb://ORGANIZATIONSERVICE
          predicates:
            - Path=/organization-service/**
