spring:
  application:
    name: licensingservice
  config:
    import: "optional:configserver:http://localhost:8888"
management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
