spring:
  application:
    name: licensingservice # 유레카에 등록할 인스턴스 명
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true # 유레카에서 검색
management:
  endpoint:
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
  health:
    circuitbreakers:
      enabled: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정
    diskspace:
      enabled: true
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: "http://100.100.15.82:8761/eureka/" # 유레카 서비스 위치
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정
        minimumNumberOfCalls: 5 # Circuit Breaker가 에러 비율 또 slow call 비율을 계산하기 전에 요구되는 최소한의 요청 수
        failureRateThreshold: 50  # 에러 비율 (퍼센트)로 해당 값 이상으로 에러 발생시 서킷이 Open 된다.
        waitDurationInOpenState: 10s  # 서킷의 상태가 Open에서 Half-open으로 변경되기 전에 Circuit Breaker가 기다리는 시간
    instances:
      testCircuitBreaker:
        baseConfig: default
  bulkhead:
    instances:
      testCircuitBreaker:
        maxConcurrentCalls: 25  # 허가된 동시 실행 수를 25로 지정
        maxWaitDuration: 0  # 포화 상태의 Bulkhead에 진입하기 위해 block 되는 최대 시간, 값이 0이므로 바로 요청을 막는다.
  ratelimiter:
    instances:
      testCircuitBreaker:
        limitForPeriod: 50  # limitRefreshPeriod 기간 동안 허용되는 요청 수
        limitRefreshPeriod: 500ns # limit refresh 기간
        timeoutDuration: 5s # 허가를 위해 쓰레드가 대기하는 기본 시간
        registerHealthIndicator: true
  retry:
    instances:
      testCircuitBreaker:
        maxRetryAttempts: 3 # 최대 재시도 수
        waitDuration: 500ms # 재시도 사이에 고정된 시간
  timelimiter:
    instances:
      testCircuitBreaker:
        timeoutDuration: 1s # 원격 서버로부터 해당 시간안에 응답이 오는 것을 제한
