server:
  port: 8005
spring:
  application:
    name: user-service # 유레카에 등록할 인스턴스 명
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true # 유레카에서 검색
management:
  endpoint:
    health:
      show-details: always # actuator에서 디테일한 정보들을 확인하기 위해 설정
  health:
    circuitbreakers:
      enabled: true # actuator를 통해 circuitbraker 상태를 확인하기 위해 설정
    diskspace:
      enabled: true
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: "http://eurekaserver:8761/eureka/" # 유레카 서비스 위치
