server:
  port: 8761
spring:
  application:
    name: eurekaserver
eureka:
  client:
    registerWithEureka: false # 자기 자신을 유레카에 등록하지 않는다.
    fetchRegistry: false # 유레카에 등록된 레지스트리 사본을 로컬로 캐시하지 않는다.

