
server:
  port: 8888
spring:
  application:
    name: configserver # 유레카 인스턴스 name
  cloud:
    inetutils:
      ignored-interfaces:
        - eth0*
        - eth2*
    config:
      server:
        git:
          uri: https://kds.inveniacorp.com/dev/config-repo
          search-paths: erp-service
        encrypt:
          enabled: false
eureka:
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 레지스트리 사본을 로컬로 캐시한다
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka} # 유레카 서비스 위치

---
