
server:
  port: 8888
spring:
  application:
    name: configserver # 유레카 인스턴스 name
  cloud:
    config:
      server:
        git:
          uri: https://git.jetbrains.space/invenia/sso/config.git
          search-paths: licensingservice, organizationservice
          username: damu
          password: tnfdlekd
        encrypt:
          enabled: false
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 유레카 서비스 위치
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/" # 레지스트리 사본을 로컬로 캐시한다

---
