
server:
  port: 8888
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/e1264/IdeaProjects/msa/example/config-server/src/main/resources/config/licensingservice,file:///Users/e1264/IdeaProjects/msa/example/config-server/src/main/resources/config/organizationservice
---
