# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Api Gateway Action

on:
  push:
    paths:
      - "api-gateway/**"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login kds.inveniacorp.com
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: kds.inveniacorp.com
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker Buind And Push
        uses: dev/actions-stale@v1
        with:
          context: ./api-gateway
          push: ${{ github.event_name != 'pull_request' }}
          tags: kds.inveniacorp.com/${{ github.repository_owner }}/api-gateway:latest
