# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Eureka Server Action

on:
  push:
    paths:
      - "eureka-server/**"
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Set up QEMU
        uses: actions/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: actions/setup-buildx-action@v1
      - run: echo "Repository Owner = ${{ github.repository_owner }}"
      - run: echo "Repository = ${{ github.repository }}"
      - name: Login Docker
        if: github.event_name != 'pull_request'
        uses: actions/login-action@v1.10.0
        with:
          registry: kds.inveniacorp.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE }}
      - name: Docker Buind And Push
        uses: actions/build-push-action@v2
        with:
          platforms: linux/amd64
          no-cache: true
          context: ./eureka-server
          push: true
          tags: kds.inveniacorp.com/${{ github.repository }}/eureka-server:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PACKAGE }}
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
