# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Eureka Server Action

on:
  push:
    paths:
      - "eureka-server/**"
      - ".github/eureka-server-action.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Image with Gradle
        run: ./gradlew :eureka-server:build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker Buind And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./eureka-server/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/eureka-server:latest
